docs: small fixes for doctor-data instructions
exercism/cpp pull request #749
Opened 2023-12-02 20:27 UTC by vaeng

Suggestions by @clechasseur

2023-12-03 03:14 UTC, clechasseur approved these changes

2023-12-03 04:50 UTC, siebenschlaefer approved these changes
If you guys really want this I'll approve. 
But I like the previous version more. The "elements" of an `enum` are called enumerators, `enum` is the type itself.

2023-12-03 10:50 UTC, vaeng commented
@siebenschlaefer
Here is @clechasseur original reasoning:
> In the first task, the text mentions an "enumerator of type System". I think the use of the term "enum" (or perhaps "enumeration") would be better, because "enumerator" is used in many languages to mean something quite different from a C++ enum.

I might go the middle way by inserting a short "reminder" about the naming convention of enums in C++ and reverting it to the original state. What do you think?

2023-12-03 16:24 UTC, siebenschlaefer commented
I don't object to this change. I understand that these concepts don't target language lawyers and that it might sense to use terms that are easier to understand than what is used in the standard.
I just wanted to give the C++ perspective where "enumerator" is the correct term (see [[dcl.enum]](https://eel.is/c++draft/enum) in the current draft of the standard.

2023-12-03 17:59 UTC, clechasseur requested changes
@siebenschlaefer After a careful reading of your comments and the provided link, I believe that the following terms should be used

- `enumeration`: refers to the type (in this case, `System`)
- `enumerator`: refers to an enum variant (in this case, `BetaHydri`)

I would therefore propose the following rephrasing, which more closely matches the standard (emphasis mine):

> The third argument comes from a `star_map` namespace.
> It is an **enumeration type** named `System`.
> You even got one of the **enumerators**: `BetaHydri`.

As an aside, I didn't know that the term _enumerator_ was used in the C++ standard to refer to an enum variant. Because of that, I thought using _enumerator_ was misleading to people coming from other languages. I do in fact like to use proper C++ terminology when possible. 🙂

2024-01-12 10:03 UTC, vaeng commented
Also add clarification to the garbled data: https://forum.exercism.org/t/corruption-in-the-c-track-repo/9088/6

2024-01-22 13:12 UTC, closed without merging