tests: update say exercise
exercism/cpp pull request #903
Opened 2024-09-22 17:58 UTC by Elahi-cs

This PR is the result of running this command:
![image](https://github.com/user-attachments/assets/915c5d0b-9bd0-4def-8642-90641135b888)

using the [test creation helper tool](https://github.com/exercism/cpp/wiki/Test-Cases-for-Practice-Exercises#test-creation-helper-tool) linked in the wiki.

2024-09-23 11:41 UTC, Elahi-cs commented
@vaeng everything should be fixed now. A couple of questions:
* I had to modify the exercise creation tool that you linked on the wiki, because it expects configlet to be on the same folder, but configlet expects to be run on the root folder of the repo. Do you see it necessary/useful to add these changes to the tool branch?
* Would it be useful to document the process to update these test cases? I'm talking setup tool -> run tool -> format with `clang-format` -> check for errors. I don't know if it's something that could be of help in the future or if it the process will be discarded once the 6 remaining exercises have their tests updated.

2024-10-04 18:39 UTC, vaeng commented
Hello @Elahi-cs,

Thanks for your patience. You did the right thing to ask in the forum and also a nudge to look at this would have been fine. 

I think your change is good and welcome, I wanted to ask the other maintainers for feedback before going further, but I haven't had the time yet.

As a result of my late reply, this September or will become tagged for hacktoberfest.

I will not be able to check your code until Tuesday, but maybe @siebenschlaefer has some capacity this weekend.

2024-10-04 21:15 UTC, ahans requested changes
The changes look mostly fine, but the two cases giving an error in CI need to be fixed.

2024-10-04 21:15 UTC, ahans commented on exercises/practice/say/say_test.cpp
> +    REQUIRE("{'error': 'input out of range'}" == say::in_english(-1));
It looks like the tool cannot handle cases with errors that well yet. For invalid input, we want the student to throw an exception.
```suggestion
    REQUIRE_THROWS_AS(say::in_english(-1), std::domain_error);
```

2024-10-04 21:15 UTC, ahans commented on exercises/practice/say/say_test.cpp
> +            say::in_english(1000000000000));
As above. Fine to reformat the number, though:
```suggestion
    REQUIRE_THROWS_AS(say::in_english(1000000000000), std::domain_error);
```

2024-10-08 10:35 UTC, ahans commented
> Related question: is there a way to run the CI tests locally? I don't like making the pipeline run the tests every time, but I also don't know if there's a good way other than using `act`.

To run exactly what happens in CI, you probably won't get around using something such as `act`. But what happens is not exactly black magic and you can check the files in `.github` to see what's going on. The actual code tests are all managed via `CMake` and run [here](https://github.com/exercism/cpp/blob/main/.github/workflows/ci.yml#L24). So if you have all the prerequisites installed, you can this locally:

```sh
cmake .
# run all tests
cmake --build .
# alternatively, run just a single test:
cmake --build . -- test_say
```

2024-10-08 10:51 UTC, vaeng approved these changes
That looks good to me, I don't see any reason not to merge this now.
@ahans remarks seem to be addressed.

2024-10-08 11:08 UTC, merged